#!/bin/bash
git add . #command for following files to be loaded
git config --global user.email "reiniskob@gmail.com"
git config --global user.name "reiniskob"
git commit -m "RTR-105a"
git push origin main

